/** Author Name: Kennedy Seijas
//Date: 01/10/2019
//Program Name: Seijas_Attendant.java
//Purpose: This is a Attendant Simulator for 5 Seats
  Each respond have 3 status, 
  * OFF, Default
  * REQUESTING FOR AN ATTENDANT : When the Seat is asking for an attendant, 
  * AN ATTENDANT IS ON THE WAY COMMING: Once The Attendant respond the call 
  From the Attendant' Screen the Control Panel of the Seats is updated.
*/

package Call_Simulator;

import java.awt.Color;


/**
 *
 * @author Master1
 */
public class Seijas_Attendants extends javax.swing.JFrame {

    /**
     * Creates new form Attendants
     */
    public Seijas_Attendants() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setLocation(1030, 280);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonSeat1 = new javax.swing.JRadioButton();
        jLabelSeatPanel = new javax.swing.JLabel();
        jLabelStatus1 = new javax.swing.JLabel();
        jRadioButtonSeat2 = new javax.swing.JRadioButton();
        jLabelStatus2 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jRadioButtonSeat3 = new javax.swing.JRadioButton();
        jLabelStatus3 = new javax.swing.JLabel();
        jButtonTurnOffAll = new javax.swing.JButton();
        jRadioButtonSeat4 = new javax.swing.JRadioButton();
        jRadioButtonSeat5 = new javax.swing.JRadioButton();
        jLabelStatus4 = new javax.swing.JLabel();
        jLabelStatus5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));

        jRadioButtonSeat1.setText("Seat 1");
        jRadioButtonSeat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat1MouseClicked(evt);
            }
        });

        jLabelSeatPanel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSeatPanel.setText("Attendants' Panel");

        jLabelStatus1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus1.setText("Off");

        jRadioButtonSeat2.setText("Seat 2");
        jRadioButtonSeat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat2MouseClicked(evt);
            }
        });

        jLabelStatus2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus2.setText("off");

        jButtonExit.setText("Exit");
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExitMouseClicked(evt);
            }
        });

        jRadioButtonSeat3.setText("Seat 3");
        jRadioButtonSeat3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat3MouseClicked(evt);
            }
        });

        jLabelStatus3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus3.setText("Off");

        jButtonTurnOffAll.setText("Turn Off all Calls");
        jButtonTurnOffAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTurnOffAllMouseClicked(evt);
            }
        });

        jRadioButtonSeat4.setText("Seat 4");
        jRadioButtonSeat4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat4MouseClicked(evt);
            }
        });

        jRadioButtonSeat5.setText("Seat 5");
        jRadioButtonSeat5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat5MouseClicked(evt);
            }
        });

        jLabelStatus4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus4.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus4.setText("Off");

        jLabelStatus5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus5.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus5.setText("Off");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSeatPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonTurnOffAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jButtonExit)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSeat1)
                    .addComponent(jRadioButtonSeat2)
                    .addComponent(jRadioButtonSeat3)
                    .addComponent(jRadioButtonSeat4)
                    .addComponent(jRadioButtonSeat5))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStatus5)
                    .addComponent(jLabelStatus4)
                    .addComponent(jLabelStatus3)
                    .addComponent(jLabelStatus2)
                    .addComponent(jLabelStatus1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelSeatPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSeat1)
                    .addComponent(jLabelStatus1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSeat2)
                    .addComponent(jLabelStatus2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSeat3)
                    .addComponent(jLabelStatus3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSeat4)
                    .addComponent(jLabelStatus4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonSeat5)
                    .addComponent(jLabelStatus5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTurnOffAll)
                    .addComponent(jButtonExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMouseClicked

    private void jRadioButtonSeat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat1MouseClicked
        // TODO add your handling code here:
        
        Seijas_Attendants.jLabelStatus1.setText("An Attendant is on the way");
        Seijas_Attendants.jLabelStatus1.setForeground(Color.green); 
        
        //Seijas_Seats seats = new Seijas_Seats();
        //Attendants.jRadioButtonSeat1.setSelected(true);
        Seijas_Seats.jLabelStatus1.setText("An Atendant is comming");
        Seijas_Seats.jLabelStatus1.setForeground(Color.green);       
              
        // if (seats.isVisible() != true)  seats.setVisible(true);
         //if (seats.isVisible() != true) {
             
         //         seats.setVisible(true);
         //}
        
        
    
    }//GEN-LAST:event_jRadioButtonSeat1MouseClicked

    private void jRadioButtonSeat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat2MouseClicked
              CheckStatus(2);
       // Attendants status
       // Seijas_Attendants.jLabelStatus2.setText("An Attendant is on the way");
        //Seijas_Attendants.jLabelStatus2.setForeground(Color.green); 
        
        //Attendants attendants = new Attendants();
        //Seijas_Seats.jLabelStatus2.setText("An Atendant is comming ");
        //Seijas_Seats.jLabelStatus2.setForeground(Color.green);            
    
        
    }//GEN-LAST:event_jRadioButtonSeat2MouseClicked

    private void jRadioButtonSeat3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat3MouseClicked
        
        // Attendants status
        Seijas_Attendants.jLabelStatus3.setText("An Attendant is on the way ");
        Seijas_Attendants.jLabelStatus3.setForeground(Color.green); 
        
        //Attendants attendants = new Attendants();
        Seijas_Seats.jLabelStatus3.setText("An Atendant is comming ");
        Seijas_Seats.jLabelStatus3.setForeground(Color.green);           

        
    }//GEN-LAST:event_jRadioButtonSeat3MouseClicked

    private void jRadioButtonSeat4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat4MouseClicked

        // Attendants status
        Seijas_Attendants.jLabelStatus4.setText("An Attendant is on the way");
        Seijas_Attendants.jLabelStatus4.setForeground(Color.green); 
        
        //Attendants attendants = new Attendants();
        Seijas_Seats.jLabelStatus4.setText("An Atendant is comming ");
        Seijas_Seats.jLabelStatus4.setForeground(Color.green);           

    }//GEN-LAST:event_jRadioButtonSeat4MouseClicked

    private void jRadioButtonSeat5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat5MouseClicked

        // Attendants status
        Seijas_Attendants.jLabelStatus5.setText("An Attendant is on the way ");
        Seijas_Attendants.jLabelStatus5.setForeground(Color.green); 
        
        //Attendants attendants = new Attendants();
        Seijas_Seats.jLabelStatus5.setText("An Atendant is comming ");
        Seijas_Seats.jLabelStatus5.setForeground(Color.green);           

    }//GEN-LAST:event_jRadioButtonSeat5MouseClicked

    private void jButtonTurnOffAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTurnOffAllMouseClicked

         //Seats seats = new Seats();
         
        //Turn Off All calls in Attendant screen
        Seijas_Attendants.jLabelStatus1.setText("Off");
        Seijas_Attendants.jLabelStatus1.setForeground(Color.red); 
        Seijas_Attendants.jRadioButtonSeat1.setSelected(false);
        
        //Turn Off All calls in Seats screen
        Seijas_Seats.jLabelStatus1.setText("Off");
        Seijas_Seats.jLabelStatus1.setForeground(Color.red);       
        Seijas_Seats.jRadioButtonSeat1.setSelected(false);

        
        //Turn Off All calls in Attendant screen
        Seijas_Attendants.jLabelStatus2.setText("Off");
        Seijas_Attendants.jLabelStatus2.setForeground(Color.red); 
        Seijas_Attendants.jRadioButtonSeat2.setSelected(false);
        
        //Turn Off All calls in Seats screen
        Seijas_Seats.jLabelStatus2.setText("Off");
        Seijas_Seats.jLabelStatus2.setForeground(Color.red);       
        Seijas_Seats.jRadioButtonSeat2.setSelected(false);
        
        
        
        //Turn Off All calls in Attendant screen
        Seijas_Attendants.jLabelStatus3.setText("Off");
        Seijas_Attendants.jLabelStatus3.setForeground(Color.red); 
        Seijas_Attendants.jRadioButtonSeat3.setSelected(false);
        
        //Turn Off All calls in Seats screen
        Seijas_Seats.jLabelStatus3.setText("Off");
        Seijas_Seats.jLabelStatus3.setForeground(Color.red);       
        Seijas_Seats.jRadioButtonSeat3.setSelected(false);

        //Turn Off All calls in Attendant screen
        Seijas_Attendants.jLabelStatus4.setText("Off");
        Seijas_Attendants.jLabelStatus4.setForeground(Color.red); 
        Seijas_Attendants.jRadioButtonSeat4.setSelected(false);
        
        //Turn Off All calls in Seats screen
        Seijas_Seats.jLabelStatus4.setText("Off");
        Seijas_Seats.jLabelStatus4.setForeground(Color.red);       
        Seijas_Seats.jRadioButtonSeat4.setSelected(false);

        
        //Turn Off All calls in Attendant screen
        Seijas_Attendants.jLabelStatus5.setText("Off");
        Seijas_Attendants.jLabelStatus5.setForeground(Color.red); 
        Seijas_Attendants.jRadioButtonSeat5.setSelected(false);
        
        //Turn Off All calls in Seats screen
        Seijas_Seats.jLabelStatus5.setText("Off");
        Seijas_Seats.jLabelStatus5.setForeground(Color.red);       
        Seijas_Seats.jRadioButtonSeat5.setSelected(false);
        
        //if (seats.isVisible() != true)  seats.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButtonTurnOffAllMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seijas_Attendants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seijas_Attendants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seijas_Attendants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seijas_Attendants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    
    
    
     private void CheckStatus (int seat){
        Seats seats = new  Seats();
        switch (seat){
            case 1:
       
                   if (seats.jRadioButtonSeat1.isSelected()) { // If Seat is on     
                       seats.jLabelStatus1.setText("An Attendant is comming CHECHECHE");
                       seats.jLabelStatus1.setForeground(Color.blue);
                       seats.jRadioButtonSeat1.setSelected(false);
                       
                      jLabelStatus1.setText("An Attendant in on the way CHECKCHECK ");
                      jLabelStatus1.setForeground(Color.blue);
                   }
                    
                      
                   
                break;
             
             case 2:
                    Seijas_Attendants.jLabelStatus2.setText("An Attendant is on the way");
                    Seijas_Attendants.jLabelStatus2.setForeground(Color.green); 
        
                    //Attendants attendants = new Attendants();
                    Seijas_Seats.jLabelStatus2.setText("An Atendant is comming ");
                    Seijas_Seats.jLabelStatus2.setForeground(Color.green);
                   
                break;
             case 3:
                    System.out.println("entro 3");

                break;                
             case 4:
                    System.out.println("entro 4");
                break;
             case 5:
                    System.out.println("entro 5");
                break;   
             default:   
        }
        
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonTurnOffAll;
    private javax.swing.JLabel jLabelSeatPanel;
    public static javax.swing.JLabel jLabelStatus1;
    public static javax.swing.JLabel jLabelStatus2;
    public static javax.swing.JLabel jLabelStatus3;
    public static javax.swing.JLabel jLabelStatus4;
    public static javax.swing.JLabel jLabelStatus5;
    public static javax.swing.JRadioButton jRadioButtonSeat1;
    public static javax.swing.JRadioButton jRadioButtonSeat2;
    public static javax.swing.JRadioButton jRadioButtonSeat3;
    public static javax.swing.JRadioButton jRadioButtonSeat4;
    public static javax.swing.JRadioButton jRadioButtonSeat5;
    // End of variables declaration//GEN-END:variables
}
