/*
Author Name: Kennedy Seijas
//Date: 01/10/2019
//Program Name: Seijas_Seats
//Purpose: This is a Call Simulator for 5 Seats
  Each seat has 3 Status, 
OFF : Default, 
  WAITING FOR AN ATTENDANT : Once the Seat Call for an Attendant, 
  ATTENDANT IS COMMING : Once the Attendant responded the call
  From the Seats' Screen the Control Panel of the attendants is udated.

 */
package Call_Simulator;

import java.awt.Color;

/**
 *
 * @author Master1
 */
public class Seijas_Seats extends javax.swing.JFrame {

    /**
     * Creates new form Seats
     */
    public Seijas_Seats() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButtonSeat1 = new javax.swing.JRadioButton();
        jRadioButtonSeat2 = new javax.swing.JRadioButton();
        jRadioButtonSeat3 = new javax.swing.JRadioButton();
        jRadioButtonSeat4 = new javax.swing.JRadioButton();
        jRadioButtonSeat5 = new javax.swing.JRadioButton();
        jLabelStatus1 = new javax.swing.JLabel();
        jLabelStatus2 = new javax.swing.JLabel();
        jLabelStatus3 = new javax.swing.JLabel();
        jLabelStatus4 = new javax.swing.JLabel();
        jLabelStatus5 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Call Seat Simulator");

        jRadioButtonSeat1.setText("Seat 1");
        jRadioButtonSeat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat1MouseClicked(evt);
            }
        });

        jRadioButtonSeat2.setText("Seat 2");
        jRadioButtonSeat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat2MouseClicked(evt);
            }
        });

        jRadioButtonSeat3.setText("Seat 3");
        jRadioButtonSeat3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat3MouseClicked(evt);
            }
        });

        jRadioButtonSeat4.setText("Seat 4");
        jRadioButtonSeat4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat4MouseClicked(evt);
            }
        });

        jRadioButtonSeat5.setText("Seat 5");
        jRadioButtonSeat5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonSeat5MouseClicked(evt);
            }
        });

        jLabelStatus1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus1.setText("Off");

        jLabelStatus2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus2.setText("Off");

        jLabelStatus3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus3.setText("Off");

        jLabelStatus4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus4.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus4.setText("Off");

        jLabelStatus5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelStatus5.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus5.setText("Off");

        jButtonExit.setText("Exit");
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSeat1)
                    .addComponent(jRadioButtonSeat2)
                    .addComponent(jRadioButtonSeat4)
                    .addComponent(jRadioButtonSeat3)
                    .addComponent(jRadioButtonSeat5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStatus2)
                    .addComponent(jLabelStatus1)
                    .addComponent(jLabelStatus3)
                    .addComponent(jLabelStatus4)
                    .addComponent(jLabelStatus5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonExit)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus1)
                    .addComponent(jRadioButtonSeat1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus2)
                    .addComponent(jRadioButtonSeat2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSeat3)
                    .addComponent(jLabelStatus3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSeat4)
                    .addComponent(jLabelStatus4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSeat5)
                    .addComponent(jLabelStatus5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMouseClicked

    private void jRadioButtonSeat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat1MouseClicked
        
        // Set Calling for Seat 1
        /** Update Status of the Seat Radio Buttons
            Update messages Labels
        */ 
        CheckStatus2(1);
                   
    }//GEN-LAST:event_jRadioButtonSeat1MouseClicked

    private void jRadioButtonSeat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat2MouseClicked
        
        /** Update Status of the Seat Radio Buttons
            Update messages Labels
        */ 
        CheckStatus2(2);
        
    }//GEN-LAST:event_jRadioButtonSeat2MouseClicked

    private void jRadioButtonSeat3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat3MouseClicked
        
        /** Update Status of the Seat Radio Buttons
            Update messages Labels
        */ 
        CheckStatus2(3);
        
        
    }//GEN-LAST:event_jRadioButtonSeat3MouseClicked

    private void jRadioButtonSeat4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat4MouseClicked
        // TODO add your handling code here:
        
        /** Update Status of the Seat Radio Buttons
            Update messages Labels
        */ 
        CheckStatus2(4);
        
        
        
    }//GEN-LAST:event_jRadioButtonSeat4MouseClicked

    private void jRadioButtonSeat5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonSeat5MouseClicked
        /** Update Status of the Seat Radio Buttons
            Update messages Labels
        */ 
        CheckStatus2(5);
        
    }//GEN-LAST:event_jRadioButtonSeat5MouseClicked

/** Date: 01/10/2019
  Program Name: Seijas_Airplane
  Method :  CheckStatus2 (int <seat>)
            int <Field> : represent the number of the seat to be updated
  Purpose: Update the fields buttons and labels of the Seats Windows and Attendants windows
*/ 
    public static void CheckStatus2 (int seat){
        
        switch (seat){
            case 1:
                // Set Calling for Seat 1
                Seijas_Seats.jLabelStatus1.setText("Waiting for an Attendant");
                Seijas_Seats.jLabelStatus1.setForeground(Color.blue); 

                //Attendants attendants = new Attendants();

                Seijas_Attendants.jLabelStatus1.setText("Requesting for an Attendant");
                Seijas_Attendants.jLabelStatus1.setForeground(Color.blue);           

                if (Seijas_Seats.jRadioButtonSeat1.isSelected() !=true) {
                    Seijas_Seats.jLabelStatus1.setText("Off");
                    Seijas_Seats.jLabelStatus1.setForeground(Color.red); 
                    Seijas_Seats.jRadioButtonSeat1.setSelected(false);

                    Seijas_Attendants.jLabelStatus1.setText("Off");
                    Seijas_Attendants.jRadioButtonSeat1.setSelected(false);            
                    Seijas_Attendants.jLabelStatus1.setForeground(Color.red); 
  
                }
               
                
                break;
             
             case 2:

                Seijas_Seats.jLabelStatus2.setText("Waiting for an Attendant");
                Seijas_Seats.jLabelStatus2.setForeground(Color.blue); 

                //Attendants attendants = new Attendants();

                Seijas_Attendants.jLabelStatus2.setText("Requesting for an Attendant");
                Seijas_Attendants.jLabelStatus2.setForeground(Color.blue);           

                if (Seijas_Seats.jRadioButtonSeat2.isSelected() !=true) {
                    Seijas_Seats.jLabelStatus2.setText("Off");
                    Seijas_Seats.jLabelStatus2.setForeground(Color.red); 
                    Seijas_Seats.jRadioButtonSeat2.setSelected(false);

                    Seijas_Attendants.jLabelStatus2.setText("Off");
                    Seijas_Attendants.jRadioButtonSeat2.setSelected(false);            
                    Seijas_Attendants.jLabelStatus2.setForeground(Color.red); 
                }
                            
                break;
             case 3:
                Seijas_Seats.jLabelStatus3.setText("Waiting for an Attendant");
                Seijas_Seats.jLabelStatus3.setForeground(Color.blue); 

                //Attendants attendants = new Attendants();
                Seijas_Attendants.jLabelStatus3.setText("Requesting for an Attendant");
                Seijas_Attendants.jLabelStatus3.setForeground(Color.blue);  

                if (Seijas_Seats.jRadioButtonSeat3.isSelected() !=true) {
                    Seijas_Seats.jLabelStatus3.setText("Off");
                    Seijas_Seats.jLabelStatus3.setForeground(Color.red); 
                    Seijas_Seats.jRadioButtonSeat3.setSelected(false);

                    Seijas_Attendants.jLabelStatus3.setText("Off");
                    Seijas_Attendants.jRadioButtonSeat3.setSelected(false);            
                    Seijas_Attendants.jLabelStatus3.setForeground(Color.red); 
                }
                 
                break;                
             case 4:
                    
                    Seijas_Seats.jLabelStatus4.setText("Waiting for an Attendant");
                    Seijas_Seats.jLabelStatus4.setForeground(Color.blue); 
       
                    //Attendants attendants = new Attendants();
                    Seijas_Attendants.jLabelStatus4.setText("Requesting for an Attendant");
                    Seijas_Attendants.jLabelStatus4.setForeground(Color.blue);  
        
                    if (Seijas_Seats.jRadioButtonSeat4.isSelected() !=true) {
                        Seijas_Seats.jLabelStatus4.setText("Off");
                        Seijas_Seats.jLabelStatus4.setForeground(Color.red); 
                        Seijas_Seats.jRadioButtonSeat4.setSelected(false);

                        Seijas_Attendants.jLabelStatus4.setText("Off");
                        Seijas_Attendants.jRadioButtonSeat4.setSelected(false);
                        Seijas_Attendants.jLabelStatus4.setForeground(Color.red); 
                    }                    
                break;
             case 5:
                    Seijas_Seats.jLabelStatus5.setText("Waiting for an Attendant");
                    Seijas_Seats.jLabelStatus5.setForeground(Color.blue); 
        
                    //Attendants attendants = new Attendants();
        
                    Seijas_Attendants.jLabelStatus5.setText("Requesting for an Attendant");
                    Seijas_Attendants.jLabelStatus5.setForeground(Color.blue);  
        
                    if (Seijas_Seats.jRadioButtonSeat5.isSelected() !=true) {
                        Seijas_Seats.jLabelStatus5.setText("Off");
                        Seijas_Seats.jLabelStatus5.setForeground(Color.red); 
                        Seijas_Seats.jRadioButtonSeat5.setSelected(false);
                        Seijas_Attendants.jLabelStatus5.setText("Off");
                        Seijas_Attendants.jRadioButtonSeat5.setSelected(false);
                        Seijas_Attendants.jLabelStatus5.setForeground(Color.red); 
                    }
                break;   
             default:   
        }
        
    }
    
        
        
        
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seijas_Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seijas_Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seijas_Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seijas_Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabelStatus1;
    public static javax.swing.JLabel jLabelStatus2;
    public static javax.swing.JLabel jLabelStatus3;
    public static javax.swing.JLabel jLabelStatus4;
    public static javax.swing.JLabel jLabelStatus5;
    public static javax.swing.JRadioButton jRadioButtonSeat1;
    public static javax.swing.JRadioButton jRadioButtonSeat2;
    public static javax.swing.JRadioButton jRadioButtonSeat3;
    public static javax.swing.JRadioButton jRadioButtonSeat4;
    public static javax.swing.JRadioButton jRadioButtonSeat5;
    // End of variables declaration//GEN-END:variables
}

